# Generated by Django 2.2.5 on 2019-10-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'in_progress'), ('3', 'done')], max_length=20),
        ),
    ]
